package tpo.logistica.wscliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-10T07:40:39.878-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "AdministradorOrdenDeDespachoBeanService", 
                  wsdlLocation = "http://localhost:8080/TPO-Despacho/AdministradorOrdenDeDespachoBean?wsdl",
                  targetNamespace = "http://ws.despacho.tpo/") 
public class AdministradorOrdenDeDespachoBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.despacho.tpo/", "AdministradorOrdenDeDespachoBeanService");
    public final static QName AdministradorOrdenDeDespachoBeanPort = new QName("http://ws.despacho.tpo/", "AdministradorOrdenDeDespachoBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/TPO-Despacho/AdministradorOrdenDeDespachoBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AdministradorOrdenDeDespachoBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/TPO-Despacho/AdministradorOrdenDeDespachoBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AdministradorOrdenDeDespachoBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministradorOrdenDeDespachoBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministradorOrdenDeDespachoBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdministradorOrdenDeDespachoBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdministradorOrdenDeDespachoBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AdministradorOrdenDeDespachoBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdministradorOrdenDeDespachoBean
     */
    @WebEndpoint(name = "AdministradorOrdenDeDespachoBeanPort")
    public AdministradorOrdenDeDespachoBean getAdministradorOrdenDeDespachoBeanPort() {
        return super.getPort(AdministradorOrdenDeDespachoBeanPort, AdministradorOrdenDeDespachoBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministradorOrdenDeDespachoBean
     */
    @WebEndpoint(name = "AdministradorOrdenDeDespachoBeanPort")
    public AdministradorOrdenDeDespachoBean getAdministradorOrdenDeDespachoBeanPort(WebServiceFeature... features) {
        return super.getPort(AdministradorOrdenDeDespachoBeanPort, AdministradorOrdenDeDespachoBean.class, features);
    }

}
