package tpo.clientes.auditoria.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T15:15:39.887-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://webServices/", name = "WSAgregarInformeAuditoriaBean")
@XmlSeeAlso({ObjectFactory.class})
public interface WSAgregarInformeAuditoriaBean {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "agregarInformeAuditoria", targetNamespace = "http://webServices/", className = "tpo.clientes.auditoria.ws.AgregarInformeAuditoria")
    @WebMethod
    @ResponseWrapper(localName = "agregarInformeAuditoriaResponse", targetNamespace = "http://webServices/", className = "tpo.clientes.auditoria.ws.AgregarInformeAuditoriaResponse")
    public boolean agregarInformeAuditoria(
        @WebParam(name = "arg0", targetNamespace = "")
        tpo.clientes.auditoria.ws.VoInformeAuditoria arg0
    );
}
