package tpo.clientes.portalweb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T13:49:20.196-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebService(targetNamespace = "http://soap/", name = "WSTTestImp")
@XmlSeeAlso({ObjectFactory.class})
public interface WSTTestImp {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "procesarVenta", targetNamespace = "http://soap/", className = "tpo.clientes.portalweb.ProcesarVenta")
    @WebMethod
    @ResponseWrapper(localName = "procesarVentaResponse", targetNamespace = "http://soap/", className = "tpo.clientes.portalweb.ProcesarVentaResponse")
    public boolean procesarVenta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
