package tpo.clientes.portalweb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7.redhat-1
 * 2014-11-08T13:49:20.227-03:00
 * Generated source version: 2.7.7.redhat-1
 * 
 */
@WebServiceClient(name = "WSTTestImpService", 
                  wsdlLocation = 123 + "http://172.16.164.43:8080/IDA_TPO_PW_SRV/WSTTestImp?wsdl",
                  targetNamespace = "http://soap/") 
public class WSTTestImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap/", "WSTTestImpService");
    public final static QName WSTTestImpPort = new QName("http://soap/", "WSTTestImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.164.43:8080/IDA_TPO_PW_SRV/WSTTestImp?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSTTestImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.164.43:8080/IDA_TPO_PW_SRV/WSTTestImp?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSTTestImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSTTestImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSTTestImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSTTestImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSTTestImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSTTestImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSTTestImp
     */
    @WebEndpoint(name = "WSTTestImpPort")
    public WSTTestImp getWSTTestImpPort() {
        return super.getPort(WSTTestImpPort, WSTTestImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTTestImp
     */
    @WebEndpoint(name = "WSTTestImpPort")
    public WSTTestImp getWSTTestImpPort(WebServiceFeature... features) {
        return super.getPort(WSTTestImpPort, WSTTestImp.class, features);
    }

}
